#!/bin/bash
pluginpath="$(dirname "$(readlink -f $0)")"

cd "$pluginpath"

OLD_HEAD=$(git show-ref HEAD | cut -d' ' -f1)
git pull
HEAD=$(git show-ref HEAD | cut -d' ' -f1)
if [ "$HEAD" != "$OLD_HEAD" ]; then
    exec $0 $@
fi

cd ..

for plugin in *; do
    [ -d "$plugin" ] || continue

    [ "$plugin" = "config" ] && continue
    cut -d' ' -f1 "$pluginpath/rc" | fgrep -q "$plugin" || {
        echo "removing $plugin"
        rm -rf "$plugin"
    }
done

cat "$pluginpath/rc" | while read line; do
    name="$(echo "$line" | cut -d' ' -f1)"
    url="$(echo "$line" | cut -d' ' -f2)"
    [ -d "$name" ] && (
        cd "$name" && echo -n "$name: " && git pull
    ) || git clone $url $name
done

for plugin in *; do
    [ -d "$plugin" ] || continue

    [ "$plugin" = "config" ] && continue
    (
        cd "$plugin"
        git submodule update --init --recursive
    )
    [ -x "$plugin/configinstall" ] && "$plugin/configinstall"
done
